version: "3.7"

services:
    app:
      container_name: back
      build: 
        context: ../
        dockerfile: ./docker/back/Dockerfile
      working_dir: /usr/src/app
      tty: true
      ports: 
      - '3000:3000'
      volumes:
        - ../app:/usr/src/app
        - nestjs-node-modules:/usr/src/app/node_modules
      command: >
          bash -c "npm run dev"

volumes:
   nestjs-node-modules: